In [14]:
YEAR = 2023

In [15]:
import os
import numpy as np
import pandas as pd

from datetime import datetime
from utils import data_processing

In [16]:
from urllib.request import urlopen

file = urlopen(f"https://raw.githubusercontent.com/mbarbetti/unifi-physics-lab3/main/data/2021/data_A1.txt")

#list_data = list()
#for line in file:
# list_data . append (line.decode("utf-8"))

#print (len(list_data))

In [17]:
files_path = f"data/private/{YEAR}_original"
export_path = f"data/{YEAR}"

df = data_processing (files_path, export_path, tdc_resolution = 1e-9)
df

   Group  TDC resolution       theta_0   theta_1
0     M1    5.000000e-09 -9.924481e-08  1.055963
1     B2    5.000000e-09 -6.641414e-08  1.021839
2     H2    5.000000e-09 -5.690786e-08  1.051252
3     G1    5.000000e-09 -8.134835e-08  0.808523
4     A2    5.000000e-09 -2.663282e-08  1.056166
5     N1    5.000000e-09 -8.829738e-08  1.160038
6     D1    5.000000e-09  8.371869e-08  1.181271
7     E2    5.000000e-09  5.135097e-08  0.849305
8     I1    5.000000e-09 -5.564944e-08  0.981317
9     C1    5.000000e-09  7.024503e-08  0.872601
10    L2    5.000000e-09 -1.322945e-08  0.941668
11    T2    5.000000e-09  8.474699e-08  0.937640
12    G2    5.000000e-09  9.002610e-08  0.961245
13    H1    5.000000e-09 -6.291599e-08  1.088742
14    B1    5.000000e-09  1.905136e-08  0.817686
15    M2    5.000000e-09  9.975680e-08  1.157949
16    D2    5.000000e-09 -7.766267e-08  1.025516
17    N2    5.000000e-09 -1.923220e-08  0.813653
18    A1    5.000000e-09  7.398600e-08  1.004149
19    E1    5.000000e-09 -6.039812e-08  1.158921
20    L1    5.000000e-09  7.724238e-08  0.930794
21    C2    5.000000e-09 -5.713182e-08  1.151221
22    I2    5.000000e-09  1.306827e-08  0.932904
23    T1    5.000000e-09  8.246850e-08  0.932500

In [18]:
timestamp = str (datetime.now()) . split (".") [0]
timestamp = timestamp . replace (" ","_")
version = ""
for time, unit in zip ( timestamp.split(":"), ["h","m","s"] ):
  version += time + unit   # YYYY-MM-DD_HHhMMmSSs

file_name = f"manipulation_{version}"

df.to_csv ( f"data/private/manipulation/{file_name}.txt", header = df.columns, index = None, sep = " " )

In [19]:
data = pd.read_csv ( f"{export_path}/data_M1.txt", header = 4, delim_whitespace = True).drop([0] )
data

            TDC          QDC1          QDC2
1      0.000009 -8.195830e-10 -8.299997e-10
2      0.000011 -8.133330e-10 -8.029163e-10
3      0.000009 -8.154163e-10 -8.154163e-10
4      0.000003 -8.174997e-10 -8.174997e-10
5      0.000002 -8.174997e-10 -8.195830e-10
...         ...           ...           ...
27160  0.000010 -9.636254e-09 -5.730002e-09
27161  0.000002 -5.309168e-09 -2.869584e-09
27162  0.000001 -1.927917e-09 -1.627917e-09
27163  0.000010 -3.444584e-09 -4.544585e-09
27164  0.000007 -4.634168e-09 -1.889375e-09

[27164 rows x 3 columns]