In [8]:
YEAR = 2023

In [9]:
import os
import numpy as np
import pandas as pd

from datetime import datetime
from utils import data_processing

In [10]:
from urllib.request import urlopen

file = urlopen(f"https://raw.githubusercontent.com/mbarbetti/unifi-physics-lab3/main/data/2021/data_A1.txt")

#list_data = list()
#for line in file:
# list_data . append (line.decode("utf-8"))

#print (len(list_data))

In [11]:
files_path = f"data/private/{YEAR}_original"
export_path = f"data/{YEAR}"

df = data_processing (files_path, export_path, tdc_resolution = 2e-9)
df

   Group  TDC resolution       theta_0   theta_1
0     M1    2.000000e-09  8.015407e-08  1.111572
1     B2    2.000000e-09 -6.762180e-08  0.968634
2     H2    2.000000e-09 -6.284355e-08  0.854408
3     G1    2.000000e-09 -7.740130e-08  0.972174
4     A2    2.000000e-09 -2.658473e-08  0.966048
5     N1    2.000000e-09  9.519674e-08  0.910690
6     D1    2.000000e-09  4.281808e-08  1.006580
7     E2    2.000000e-09 -1.326708e-08  1.173270
8     I1    2.000000e-09 -7.949023e-08  1.122558
9     C1    2.000000e-09  8.663516e-08  1.136333
10    L2    2.000000e-09  9.330187e-08  1.067299
11    T2    2.000000e-09  7.559899e-08  0.988206
12    G2    2.000000e-09  2.494947e-08  0.827118
13    H1    2.000000e-09 -1.598372e-08  0.921069
14    B1    2.000000e-09 -8.317366e-08  0.825502
15    M2    2.000000e-09 -2.221092e-08  1.113351
16    D2    2.000000e-09 -7.587950e-08  0.851093
17    N2    2.000000e-09  4.453837e-08  1.117417
18    A1    2.000000e-09  4.454890e-08  0.837859
19    E1    2.000000e-09 -7.491019e-08  1.095594
20    L1    2.000000e-09  9.092548e-08  0.883205
21    C2    2.000000e-09  1.527705e-08  1.027947
22    I2    2.000000e-09  9.378570e-08  0.932679
23    T1    2.000000e-09 -1.652877e-08  1.009817

In [12]:
timestamp = str (datetime.now()) . split (".") [0]
timestamp = timestamp . replace (" ","_")
version = ""
for time, unit in zip ( timestamp.split(":"), ["h","m","s"] ):
  version += time + unit   # YYYY-MM-DD_HHhMMmSSs

file_name = f"manipulation_{version}"

df.to_csv ( f"data/private/manipulation/{file_name}.txt", header = df.columns, index = None, sep = " " )

In [13]:
data = pd.read_csv ( f"{export_path}/data_M1.txt", header = 4, delim_whitespace = True).drop([0] )
data

            TDC          QDC1          QDC2
1      0.000010 -8.195830e-10 -8.299997e-10
2      0.000011 -8.133330e-10 -8.029163e-10
3      0.000010 -8.154163e-10 -8.154163e-10
4      0.000004 -8.174997e-10 -8.174997e-10
5      0.000003 -8.174997e-10 -8.195830e-10
...         ...           ...           ...
27160  0.000011 -9.636254e-09 -5.730002e-09
27161  0.000002 -5.309168e-09 -2.869584e-09
27162  0.000002 -1.927917e-09 -1.627917e-09
27163  0.000010 -3.444584e-09 -4.544585e-09
27164  0.000008 -4.634168e-09 -1.889375e-09

[27164 rows x 3 columns]